# SEE: https://docs.travis-ci.com/user/languages/ruby/

language: ruby
rvm:
  - 2.5.3
before_install:
  - gem install bundler:1.17.3
install:
  - bundle _1.17.3_ install --jobs=3 --retry=3
  - bundle exec rake db:reset
env:
  - 'TEST_RAILS_VERSION="~> 5.2.3"'
  - 'TEST_RAILS_VERSION="~> 6.0.3"'
  - 'TEST_RAILS_VERSION="~> 6.1.3.2"'
